SiteTitle: zunderscore.tv
PageTitle: |
  =>
  {
    string siteTitle = Context.GetString("SiteTitle");
    string title = GetString("Title");
    return string.IsNullOrWhiteSpace(siteTitle) ? title : (string.IsNullOrWhiteSpace(title) ? siteTitle : $"{title} - {siteTitle}");
  }
Copyright: => $"Copyright © {DateTime.Now.Year} zundermedia, LLC"
Layout: /_layout.cshtml